"""initial schema

Revision ID: 900130a6de91
Revises: 
Create Date: 2026-07-29 22:24:06.012409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900130a6de91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('cost_class', sa.String(), nullable=False),
    sa.Column('purchase_unit', sa.String(), nullable=False),
    sa.Column('usage_unit', sa.String(), nullable=False),
    sa.Column('fabric_width_cm', sa.Numeric(), nullable=True),
    sa.Column('current_avg_cost', sa.Numeric(), nullable=False),
    sa.Column('reorder_min_qty', sa.Numeric(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('sales_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_no', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('marketplace_fee_pct', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('supplier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material_purchase',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('width_cm', sa.Numeric(), nullable=True),
    sa.Column('length_cm', sa.Numeric(), nullable=True),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('package_label', sa.Text(), nullable=True),
    sa.Column('total_cost', sa.Numeric(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=False),
    sa.Column('remaining_length_cm', sa.Numeric(), nullable=True),
    sa.Column('remaining_qty', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_size',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('size_label', sa.Text(), nullable=False),
    sa.Column('fabric_variant_name', sa.Text(), nullable=True),
    sa.Column('reorder_min_qty', sa.Numeric(), nullable=True),
    sa.Column('selling_price', sa.Numeric(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size_label', 'fabric_variant_name')
    )
    op.create_table('cutting_layout',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_purchase_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('waste_pct', sa.Numeric(), nullable=True),
    sa.Column('total_fabric_cost', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_purchase_id'], ['material_purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern_spec',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_size_id', sa.UUID(), nullable=False),
    sa.Column('fabric_material_id', sa.UUID(), nullable=False),
    sa.Column('cut_width_cm', sa.Numeric(), nullable=False),
    sa.Column('cut_height_cm', sa.Numeric(), nullable=False),
    sa.Column('rotation_allowed', sa.Boolean(), nullable=False),
    sa.Column('est_labor_minutes', sa.Numeric(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fabric_material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('product_size_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('discount', sa.Numeric(), nullable=False),
    sa.Column('unit_hpp_snapshot', sa.Numeric(), nullable=False),
    sa.Column('line_profit', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_size.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_size_id', sa.UUID(), nullable=False),
    sa.Column('change_qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('ref_type', sa.String(), nullable=True),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('unit_hpp_snapshot', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cutting_layout_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cutting_layout_id', sa.UUID(), nullable=False),
    sa.Column('product_size_id', sa.UUID(), nullable=False),
    sa.Column('pattern_spec_id', sa.UUID(), nullable=False),
    sa.Column('orientation', sa.String(), nullable=False),
    sa.Column('qty_suggested', sa.Integer(), nullable=False),
    sa.Column('fabric_length_used_cm', sa.Numeric(), nullable=False),
    sa.Column('cost_per_piece', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['cutting_layout_id'], ['cutting_layout.id'], ),
    sa.ForeignKeyConstraint(['pattern_spec_id'], ['pattern_spec.id'], ),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern_component',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pattern_spec_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('qty_per_unit', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['pattern_spec_id'], ['pattern_spec.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cutting_layout_id', sa.UUID(), nullable=True),
    sa.Column('produced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cutting_layout_id'], ['cutting_layout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_batch_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('production_batch_id', sa.UUID(), nullable=False),
    sa.Column('product_size_id', sa.UUID(), nullable=False),
    sa.Column('pattern_spec_id', sa.UUID(), nullable=False),
    sa.Column('qty_actual', sa.Integer(), nullable=False),
    sa.Column('cutting_layout_item_id', sa.UUID(), nullable=True),
    sa.Column('material_purchase_id', sa.UUID(), nullable=False),
    sa.Column('fabric_cost_per_piece', sa.Numeric(), nullable=False),
    sa.Column('fabric_length_per_unit_cm', sa.Numeric(), nullable=False),
    sa.Column('hpp_fabric', sa.Numeric(), nullable=False),
    sa.Column('hpp_pooled_material', sa.Numeric(), nullable=False),
    sa.Column('hpp_hardware', sa.Numeric(), nullable=False),
    sa.Column('hpp_labor', sa.Numeric(), nullable=False),
    sa.Column('hpp_overhead', sa.Numeric(), nullable=False),
    sa.Column('hpp_total', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['cutting_layout_item_id'], ['cutting_layout_item.id'], ),
    sa.ForeignKeyConstraint(['material_purchase_id'], ['material_purchase.id'], ),
    sa.ForeignKeyConstraint(['pattern_spec_id'], ['pattern_spec.id'], ),
    sa.ForeignKeyConstraint(['product_size_id'], ['product_size.id'], ),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_batch_item')
    op.drop_table('production_batch')
    op.drop_table('pattern_component')
    op.drop_table('cutting_layout_item')
    op.drop_table('stock_ledger')
    op.drop_table('sales_order_item')
    op.drop_table('pattern_spec')
    op.drop_table('cutting_layout')
    op.drop_table('product_size')
    op.drop_table('material_purchase')
    op.drop_table('supplier')
    op.drop_table('settings')
    op.drop_table('sales_order')
    op.drop_table('product')
    op.drop_table('owner_account')
    op.drop_table('material')
    # ### end Alembic commands ###
