"""Add event price adjustment settings

Revision ID: c066b5a8ea5a
Revises: b5d06862784d
Create Date: 2026-09-15 16:55:01.567415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c066b5a8ea5a'
down_revision: Union[str, None] = 'b5d06862784d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_material_fabric_family', table_name='material', postgresql_where='(fabric_family IS NOT NULL)')
    op.drop_index('ix_material_usage_log_material_id', table_name='material_usage_log')
    op.drop_index('idx_pattern_spec_fabric_spec_id', table_name='pattern_spec_fabric')
    op.drop_index('idx_product_size_image_size_id', table_name='product_size_image')
    op.drop_index('idx_pbl_batch', table_name='production_batch_layout')
    op.drop_constraint('uq_pbl_batch_layout', 'production_batch_layout', type_='unique')
    op.alter_column('settings', 'value',
               existing_type=sa.NUMERIC(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'value',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_unique_constraint('uq_pbl_batch_layout', 'production_batch_layout', ['production_batch_id', 'cutting_layout_id'])
    op.create_index('idx_pbl_batch', 'production_batch_layout', ['production_batch_id'], unique=False)
    op.create_index('idx_product_size_image_size_id', 'product_size_image', ['product_size_id'], unique=False)
    op.create_index('idx_pattern_spec_fabric_spec_id', 'pattern_spec_fabric', ['pattern_spec_id'], unique=False)
    op.create_index('ix_material_usage_log_material_id', 'material_usage_log', ['material_id'], unique=False)
    op.create_index('ix_material_fabric_family', 'material', ['fabric_family'], unique=False, postgresql_where='(fabric_family IS NOT NULL)')
    # ### end Alembic commands ###
