"""make fabric_cost_per_piece nullable

Revision ID: f8a7b9c1d2e3
Revises: f7bc124c44a8
Create Date: 2026-08-21 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a7b9c1d2e3'
down_revision: Union[str, None] = 'f7bc124c44a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_batch_item', 'fabric_cost_per_piece',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_batch_item', 'fabric_cost_per_piece',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
